"""ch

Revision ID: 998bfacdca8b
Revises: 
Create Date: 2023-06-17 15:18:08.437580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998bfacdca8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userBooking', schema=None) as batch_op:
        batch_op.alter_column('booking_time',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('numberSeats',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userBooking', schema=None) as batch_op:
        batch_op.alter_column('numberSeats',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('booking_time',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
